#
###################################
# Site wide configuration
####################################
#
title: bsinky blog
email:
description: A blog about programming, and probably video games
# the base hostname & protocol for your site
# If your project is placed in https://github.com/yourname/yourname.github.io at master branch
# Then, the 'url' is: http://yourname.github.io
# If your project is placed in another repository as a gh-pages branch, like: https://github.com/yourname/projectname
# Then, the 'url' is: http://yourname.github.io/projectname
url: https://bsinky.github.io

#
###################################
# Jekyll configuration
####################################
#
timezone:    America/Chicago
markdown:    kramdown
highlighter:  rouge
excerpt_separator: <!--more-->

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Benjamin Sinkula
  avatar: avatar.jpg
  job: "Software Engineer, Web Developer"
  bio: 
  email:
  disqus-shortname: bsinkyblog
  twitter: 
  facebook: 
  google:
    plus: 
    analytics: UA-101240207-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: bsinky
  stackoverflow: 4276832/bsinky
  linkedin: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: bsinky
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
  reddit: bsinky
